### ISSUE TITLE
Путь к первой демо версии

### ISSUE THREAD

**Issue by VladmirV** [VladmirV/AR_Dev#11]
Выполнить:
- [x] Интеграция базы данных в проект
- [x] Реализация реагирования приложения на метки
- [x] Возможность влиять на поведение моделей (вращение)
- [x] Первая версия виртуального гида

Результатом является PR с файлами проекта.

**Comment by VladmirV** [comment]
Открыта подзадача #15

**Comment by VladmirV** [comment]
Открыта подзадача #16

**Comment by VladmirV** [comment]
Открыта подзадача #17

**Comment by VladmirV** [comment]
Открыта подзадача #18

**Comment by VladmirV** [comment]
Открыта подзадача #19

**Comment by VladmirV** [comment]
Открыта подзадача #20

**Comment by VladmirV** [comment]
Задача выполнена.
