### ISSUE TITLE
Путь к релизу

### ISSUE THREAD

**Issue by VladmirV** [VladmirV/AR_Dev#13]
- [x] Адаптировать изменения под другие модели.
- [x] Улучшить вращение фигур
- [x] Доделать гида
- [x] Интегрировать гида в проект

**Comment by VladmirV** [comment]
Открыта подзадача #22

**Comment by VladmirV** [comment]
Открыта подзадача #23

**Comment by VladmirV** [comment]
Открыта подзадача #24

**Comment by VladmirV** [comment]
Открыта подзадача #25

**Comment by VladmirV** [comment]
Задача выполнена.
